// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/cart": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the user's cart grouped by cart order and markets. Requires user JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Get user cart",
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds or updates a product in the user's cart for a market under a single cart order. Requires user JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Add to cart",
                "parameters": [
                    {
                        "description": "Cart entry details",
                        "name": "cart",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CartRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes all cart entries for the authenticated user. Requires user JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Clear cart",
                "responses": {}
            }
        },
        "/api/cart-product/{size_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a specific cart entry for the authenticated user based on size_id. Requires user JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Delete cart entry by size_id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Size ID",
                        "name": "size_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/cart/{cart_order_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes all entries for a user's cart order by cart_order_id. Requires user JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Delete cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cart Order ID",
                        "name": "cart_order_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/cart/{cart_order_id}/order": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submits an order for a cart order with location and user details. Requires user JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Create order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cart Order ID",
                        "name": "cart_order_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Order details",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.OrderRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/cart/{size_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the count of a specific cart entry for the authenticated user based on size_id. Requires user JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Update cart entry count",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Size ID",
                        "name": "size_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Count change",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateCartRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/favorites": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a paginated list of favorite products. Requires JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favorites"
                ],
                "summary": "Get user's favorite products",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds or removes a product from favorites. Requires JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favorites"
                ],
                "summary": "Toggle favorite product",
                "parameters": [
                    {
                        "description": "Product ID",
                        "name": "favorite",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.FavoriteRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/locations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all locations for the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Locations"
                ],
                "summary": "Get user locations",
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a new location with name and address for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Locations"
                ],
                "summary": "Add location",
                "parameters": [
                    {
                        "description": "Location details",
                        "name": "location",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.LocationRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/locations/{location_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the name and/or address of a specific location for the authenticated user. Requires user JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Locations"
                ],
                "summary": "Update location",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Location ID",
                        "name": "location_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Location update details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateLocationRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a specific location for the authenticated user if no orders reference it. Requires user JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Locations"
                ],
                "summary": "Delete location",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Location ID",
                        "name": "location_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/market/markets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves market details and its products by market ID with pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Markets"
                ],
                "summary": "Get market by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of products per page (default: 20, min: 1, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1, min: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page number",
                        "name": "category_id",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/market/markets/{id}/thumbnail": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Uploads a thumbnail image for a specific market. Requires JWT authentication.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Markets"
                ],
                "summary": "Upload market thumbnail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Thumbnail image",
                        "name": "thumbnail",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/market/messages": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new message from a market to superadmin. Requires market admin JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market Messages"
                ],
                "summary": "Create a new market message",
                "parameters": [
                    {
                        "description": "Message details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateMarketMessageRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/market/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all orders for the market admin's market, optionally filtered by status. Requires market admin JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Get market admin orders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order status (pending, delivered, cancelled)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/market/orders/{order_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves detailed order information for a specific order_id. Requires market admin JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Get market admin order by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the status of an order to 'canceled' or 'delivered'. Requires market admin JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Update order status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Order status update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateOrderStatusRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a order by its ID. Requires JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Delete a order by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/market/products": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new product for the market admin's market with an optional thumbnail. Requires JWT authentication.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Create a new product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Product name in Russian",
                        "name": "name_ru",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Product price",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Product discount (0-100)",
                        "name": "discount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Product description",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Product description in Russian",
                        "name": "description_ru",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "category_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Is product active",
                        "name": "is_active",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Thumbnail image",
                        "name": "thumbnail",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/api/market/products/{id}/thumbnails": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds multiple thumbnail images with associated colors to a product by ID. Requires JWT authentication.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Add thumbnails to a product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of colors for thumbnails",
                        "name": "colors",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of colors_ru for thumbnails",
                        "name": "colors_ru",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Thumbnail images",
                        "name": "thumbnails",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/market/products/{product_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a product for the market admin's market, including its thumbnail image. Requires JWT authentication.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Update a product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "category_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Product name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Product name (Russian)",
                        "name": "name_ru",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Product price",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Discount percentage",
                        "name": "discount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Product description",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Product description (Russian)",
                        "name": "description_ru",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "Product active status",
                        "name": "is_active",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Thumbnail image",
                        "name": "thumbnail",
                        "in": "formData"
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a product and its thumbnails for the market admin's market. Requires JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Delete a product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/market/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the market profile data for the authenticated market admin. Requires market admin JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market"
                ],
                "summary": "Get market profile",
                "responses": {}
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the market profile data (except phone) for the authenticated market admin. Supports thumbnail file upload. Requires market admin JWT authentication.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market"
                ],
                "summary": "Update market profile",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Delivery price",
                        "name": "delivery_price",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Market name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Market name in Russian",
                        "name": "name_ru",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Market location",
                        "name": "location",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Market location in Russian",
                        "name": "location_ru",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Thumbnail image (PNG/JPEG, max 5MB)",
                        "name": "thumbnail",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/api/market/sizes/{size_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the count, price, and size of a size entry. Requires market admin JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Markets"
                ],
                "summary": "Update a size",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Size ID",
                        "name": "size_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Size update details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateSizeRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a size by its ID. Requires JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Delete a size by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Size ID",
                        "name": "size_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/market/thumbnails/{thumbnail_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a thumbnail’s color, color_ru, and image. Deletes the old image and uploads a new one. Requires market admin JWT authentication.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Markets"
                ],
                "summary": "Update a thumbnail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Thumbnail ID",
                        "name": "thumbnail_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Color for thumbnail",
                        "name": "color",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Color_ru for thumbnail",
                        "name": "color_ru",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "New thumbnail image",
                        "name": "thumbnail",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a thumbnail by its ID. Requires JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Delete a thumbnail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thumbnail ID",
                        "name": "thumbnail_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/market/thumbnails/{thumbnail_id}/size": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a size with count linked to a thumbnail. Requires JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Add a size by thumbnail ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thumbnail ID",
                        "name": "thumbnail_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Size and count",
                        "name": "size",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SizeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/messages": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new message to superadmin. Requires user JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Messages"
                ],
                "summary": "Create a new message",
                "parameters": [
                    {
                        "description": "Message details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateMessageRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the full_name, phone, and id of the authenticated user. Requires user JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Get user profile",
                "responses": {}
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the full_name and/or phone of the authenticated user. Requires user JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "description": "Profile update details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/superadmin/banners": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new banner with a description and thumbnail image. Requires superadmin JWT authentication.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Banners"
                ],
                "summary": "Create a new banner",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Banner description (max 255 characters)",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Thumbnail image (PNG/JPEG, max 5MB)",
                        "name": "thumbnail",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/superadmin/banners/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a banner by ID and removes its thumbnail image. Requires superadmin JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Banners"
                ],
                "summary": "Delete a banner",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Banner ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/superadmin/categories": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a category with name and optional thumbnail image. Requires superadmin JWT authentication.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Create a new category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Category name_ru",
                        "name": "name_ru",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Thumbnail image",
                        "name": "thumbnail",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/api/superadmin/categories/{category_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a category and its thumbnail image. Requires superadmin JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Delete a category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/superadmin/market-messages": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all messages sent by markets to superadmin. Requires superadmin JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market Messages"
                ],
                "summary": "Get all market messages",
                "responses": {}
            }
        },
        "/api/superadmin/market-messages/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a specific market message by ID. Requires superadmin JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market Messages"
                ],
                "summary": "Delete a market message",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/superadmin/markets": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new market with an admin account and optional thumbnail image. Requires superadmin JWT authentication.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Markets"
                ],
                "summary": "Create a new market",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Market name russian",
                        "name": "name_ru",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Market location",
                        "name": "location",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Market location russian",
                        "name": "location_ru",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Admin phone",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Delivery price",
                        "name": "delivery_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Admin password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Thumbnail image",
                        "name": "thumbnail",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/api/superadmin/markets/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a market by ID, including its thumbnail image. Requires superadmin JWT authentication.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Markets"
                ],
                "summary": "Update a market",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Market password",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Delivery price",
                        "name": "delivery_price",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Phone number",
                        "name": "phone",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Market name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Market name (Russian)",
                        "name": "name_ru",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Location",
                        "name": "location",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Location (Russian)",
                        "name": "location_ru",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "VIP status",
                        "name": "isVIP",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Thumbnail image",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a market, its products, and thumbnails. Requires superadmin JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Markets"
                ],
                "summary": "Delete a market",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/superadmin/user-messages": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all messages sent by users to superadmin. Requires superadmin JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Messages"
                ],
                "summary": "Get all user messages",
                "responses": {}
            }
        },
        "/api/superadmin/user-messages/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a specific user message by ID. Requires superadmin JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Messages"
                ],
                "summary": "Delete a user message",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/superadmin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a paginated list of users with optional search by full_name, phone, or ID. Requires superadmin authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Superadmin"
                ],
                "summary": "Get all users",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term to filter by full_name, phone, or ID",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/superadmin/users/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the verified status of a user by ID. Requires superadmin authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Superadmin"
                ],
                "summary": "Update user verified status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Verified status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserVerifiedRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a user by ID. Requires superadmin authentication.",
                "tags": [
                    "Superadmin"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/user-orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all orders for the market admin's market, optionally filtered by status. Requires market admin JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Get market admin orders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order status (pending, delivered, cancelled)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/user-orders/{order_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the is_active of an order to false",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Update order is_active",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/banners": {
            "get": {
                "description": "Retrieves all banners with their ID, description, and thumbnail URL. Public endpoint, no authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Banners"
                ],
                "summary": "Get all banners",
                "responses": {}
            }
        },
        "/categories": {
            "get": {
                "description": "Retrieves a paginated list of categories with optional name search. Requires superadmin JWT authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Get categories",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by category name",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/login": {
            "post": {
                "description": "Initiates login by sending a verification code to the user's phone number. Checks if the phone is registered and logs the code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Initiate user login",
                "parameters": [
                    {
                        "description": "User login details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.LoginRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/market/login": {
            "post": {
                "description": "Authenticates a market admin and returns a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login market admin",
                "parameters": [
                    {
                        "description": "Market admin credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.MarketRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/markets": {
            "get": {
                "description": "Retrieves a list of all markets. Requires JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Markets"
                ],
                "summary": "Get all markets",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Duration day for new (default: 7)",
                        "name": "duration",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter new markets (default: false)",
                        "name": "is_new",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter vip markets (default: false)",
                        "name": "is_vip",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/markets/{id}": {
            "get": {
                "description": "Retrieves market details and its products by market ID with pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Markets"
                ],
                "summary": "Get market by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of products per page (default: 20, min: 1, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1, min: 1)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/products": {
            "get": {
                "description": "Retrieves paginated products with optional category, price range, discount, new status, sorting, name search, or random selection for homepage",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Get all products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Market ID",
                        "name": "market_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Duration day for new (default: 7)",
                        "name": "duration",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1, ignored if random=true)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 10, ignored if random=true)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by product name",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Return 10 random products (default: false)",
                        "name": "random",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum final price",
                        "name": "start_price",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum final price",
                        "name": "end_price",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order: cheap_to_expensive, expensive_to_cheap (default: by ID)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter products with discount (default: false)",
                        "name": "has_discount",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter new products (default: false)",
                        "name": "is_new",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/products/{id}": {
            "get": {
                "description": "Retrieves a single product by its ID. Requires JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Get a product by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/register": {
            "post": {
                "description": "Registers a new user with a full name and phone number, sending a verification code. Validates input, checks for duplicate phone numbers, and logs the code (replace with SMS in production).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RegisterRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/superadmin/login": {
            "post": {
                "description": "Authenticates a superadmin and returns a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Superadmin"
                ],
                "summary": "Login superadmin",
                "parameters": [
                    {
                        "description": "Superadmin credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SuperadminRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/superadmin/register": {
            "post": {
                "description": "Registers a new superadmin with username, full name, phone, and password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Superadmin"
                ],
                "summary": "Register a new superadmin",
                "parameters": [
                    {
                        "description": "Superadmin details",
                        "name": "superadmin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SuperadminRegisterRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/thumbnails": {
            "get": {
                "description": "Retrieves a list of all thumbnails with associated product information. Requires JWT authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Get all thumbnails with product details",
                "responses": {}
            }
        },
        "/verify": {
            "post": {
                "description": "Verifies a phone number using a 4-digit code, issuing a JWT token upon successful verification. Deletes the used code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Verify phone number",
                "parameters": [
                    {
                        "description": "Verification details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.VerifyCodeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "api.FavoriteRequest": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "integer"
                }
            }
        },
        "api.LocationRequest": {
            "type": "object",
            "properties": {
                "location_address": {
                    "type": "string"
                },
                "location_address_ru": {
                    "type": "string"
                },
                "location_name": {
                    "type": "string"
                },
                "location_name_ru": {
                    "type": "string"
                }
            }
        },
        "api.LoginRequest": {
            "type": "object",
            "required": [
                "phone"
            ],
            "properties": {
                "phone": {
                    "type": "string",
                    "example": "+12345678901"
                }
            }
        },
        "api.MarketRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "api.OrderRequest": {
            "type": "object",
            "properties": {
                "location_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "api.RegisterRequest": {
            "type": "object",
            "required": [
                "full_name",
                "phone"
            ],
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "phone": {
                    "type": "string",
                    "example": "+12345678901"
                }
            }
        },
        "api.SizeRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "size": {
                    "type": "string"
                }
            }
        },
        "api.SuperadminRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.VerifyCodeRequest": {
            "type": "object",
            "required": [
                "code",
                "phone"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "1234"
                },
                "phone": {
                    "type": "string",
                    "example": "+12345678901"
                }
            }
        },
        "models.CartRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "integer"
                },
                "size_id": {
                    "type": "integer"
                },
                "thumbnail_id": {
                    "type": "integer"
                }
            }
        },
        "models.CreateMarketMessageRequest": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.CreateMessageRequest": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.SuperadminRegisterRequest": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UpdateCartRequest": {
            "type": "object",
            "properties": {
                "count_change": {
                    "type": "integer"
                }
            }
        },
        "models.UpdateLocationRequest": {
            "type": "object",
            "properties": {
                "location_address": {
                    "type": "string"
                },
                "location_address_ru": {
                    "type": "string"
                },
                "location_name": {
                    "type": "string"
                },
                "location_name_ru": {
                    "type": "string"
                }
            }
        },
        "models.UpdateOrderStatusRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "models.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.UpdateSizeRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "size": {
                    "type": "string"
                }
            }
        },
        "models.UpdateUserVerifiedRequest": {
            "type": "object",
            "properties": {
                "verified": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer token for authentication (e.g., \"Bearer \u003ctoken\u003e\")",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "192.168.55.42:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "E-commerce API",
	Description:      "API for an e-commerce platform with OTP-based authentication and product/market management.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
